### ISSUE TITLE
[Log] 로그 백업 자동화

### ISSUE THREAD

**Issue by Youhoseong** [CCC-org/keewe-backend#35]
logback-spring 설정추가

**Comment by byeongdori** [comment]
https://www.elastic.co/kr/cloud/ 

이거 쓰면 로그보기 좋아요

**Comment by kimyoungi99** [comment]
[](url)

> https://www.elastic.co/kr/cloud/
> 
> 이거 쓰면 로그보기 좋아요

사랑합니다~
